spring:
    datasource:
        url: jdbc:mariadb://smingjob.csgjnxajgfhs.ap-northeast-2.rds.amazonaws.com:3306/smingjob
        driverClassName: org.mariadb.jdbc.Driver
        username: smingjob
        password: smingjob
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
    port: 9000

logging:
    level:
        org.springframework.security: debug